django-mytunes/mysite/mysite/urls.py
from django.views.generic.base import TemplateView # new
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include # new


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tunes/', include('tunes.urls')),
    path('', TemplateView.as_view(template_name='tunes/home_page.html'), name='home'),
]

django-mytunes/mysite/tunes/urls.py
from django.urls import path

from . import views

app_name = 'tunes'
urlpatterns = [    
    path('', views.home, name='home'),

    path('artist/', views.browse_by_artist, name = 'all_artists'),
    path('artist/<int:artist_id>', views.detail_artist, name = 'specific_artist'),

    path('album/', views.browse_by_album, name = 'all_albums'),
    path('album/<int:album_id>', views.detail_album, name = "specific_album"),

    path('genre/', views.browse_by_genre, name = 'all_genres'),
    path('genre/<int:genre_id>', views.detail_genre, name = "specific_genre"),

    path('playlist/', views.browse_by_playlist, name = 'all_playlists'),
    path('playlist/<int:playlist_id>/', views.detail_playlist, name = 'specific_playlist'),

    path('track/', views.browse_by_track, name = 'all_tracks'),
    path('track/<int:track_id>/', views.detail_track, name = "specific_track"),

    path('shareplaylist/<int:playlist_id>/', views.shareplaylist, name = "share_specific")

]

django-mytunes/mysite/tunes/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Artist(models.Model):

    name = models.CharField(max_length = 120)
    
    def __str__(self):
        return self.name

class Album(models.Model):

    title = models.CharField(max_length = 160)
    artist = models.ForeignKey(Artist, null = True, blank = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

class Genre(models.Model):

    name = models.CharField(max_length = 120)
    
    def __str__(self):
        return self.name
    
class Track(models.Model):

    name = models.CharField(max_length = 200)
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    genre = models.ForeignKey(Genre, null = True, blank = True, on_delete = models.SET_NULL)
    composer = models.CharField(null = True, blank = True, max_length = 220)
    milliseconds = models.IntegerField()

    def __str__(self):
        return self.name
    
    
class Playlist(models.Model):

    name = models.CharField(max_length = 120)
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "owned_list")
    shared_with = models.ManyToManyField(User, related_name = "shared_list")
    tracks = models.ManyToManyField(Track)

    def __str__(self):
        return self.name

class SharedRequest(models.Model):
    userrequesting = models.ForeignKey(User)
    acceptrequest = models.BooleanField()
    blockrequest = models.BooleanField()
    blockrequester = models.ForeignKey(User)

django-mytunes/mysite/tunes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.db.models import Count
import sqlite3
from django.contrib.auth.models import User

from .models import Track, Artist, Album, Genre, Playlist, SharedRequest
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request,'tunes/home_page.html')

## Playlist Function ##
@login_required(login_url = "/accounts/login/")

def browse_by_playlist(request):
    errormessage = ""
    if request.method == "POST" and Playlist.objects.filter(name = request.POST['name'], user = request.user).count() > 0:
        errormessage = "You already have a playlist by that name, please choose a diffferent name."
    elif request.method == "POST":
        newp = Playlist(name = request.POST["name"], user = request.user)
        newp.save()

    playlists = list(Playlist.objects.filter(user = request.user))
    sharedplaylists = list(Playlist.objects.filter(shared_with = request.user))
    return render(request, 'tunes/playlist.html', {'playlists': playlists, 'msg':errormessage, "shared": sharedplaylists})

def detail_playlist(request, playlist_id):
    if request.method == "POST":
        Playlist.objects.get(id = playlist_id).tracks.add(Track.objects.get(id = request.POST["track"]))
    playlist = Playlist.objects.get(id = playlist_id)
    tracks = list(Track.objects.all())

    return render(request, 'tunes/playlistdetail.html', {'playlist': playlist, 'tracks':tracks})


## Genre Functions ##
def browse_by_genre(request):

    genres = list(Genre.objects.all())

    return render(request, 'tunes/genre.html', {'genres': genres})

def detail_genre(request, genre_id):

    genretracks = list(Track.objects.filter(genre_id = genre_id))

    return render(request, 'tunes/genredetail.html', {'genre': genretracks})


## Artist Functions ## 
def browse_by_artist(request):
    artists = Artist.objects.all().annotate(tracks = Count('album__track'))
    return render(request, 'tunes/artist.html', context = {'artists': artists})

def detail_artist(request, artist_id):
    trackslist = list(Track.objects.filter(album__artist_id = artist_id))
    albumslist = list(Album.objects.filter(artist_id = artist_id))
    artist = Artist.objects.get(id = artist_id)
    return render(request, 'tunes/artistdetail.html', context = {'trackslist': trackslist, 'albumslist':albumslist, 'artist':artist})

## Album Funtions ##
def browse_by_album(request):

    albums = Album.objects.all().annotate(numtracks = Count('track'))

    return render(request, 'tunes/album.html', context =  {'albums': albums})
    
def detail_album(request, album_id):

    album = Album.objects.get(id = album_id)

    return render(request, 'tunes/albumdetail.html', context = {"album": album})

## Track Functions ##
def browse_by_track(request):
    tracks = list(Track.objects.all())
    
    return render(request, 'tunes/track.html', {'tracks': tracks})


def detail_track(request, track_id):

    track = Track.objects.get(id = track_id)

    return render(request, 'tunes/trackdetail.html', {'track': track})

"""
def shareanyplaylist(request):
    playlistList = Playlist.objects.filter(user = request.user)
    return render(request, "tunes/share.html", {'playlists': playlistList})
"""
def shareplaylist(request, playlist_id):
    if request.method == "POST":
        Playlist.objects.get(id = playlist_id).shared_with.add(User.objects.get(id = request.POST["name"]))
    allusers = User.objects.exclude(id = request.user.id)
    playlist = Playlist.objects.get(id = playlist_id)
    return render(request, 'tunes/sharespecific.html', {'playlist': playlist, 'allusers':allusers})

def socials(request):
    if request.method == "POST":
        SharedRequest

django-mytunes/mysite/templates/regi/login.html
{% extends 'tunes/base_template.html' %}

{% block title %}

{% endblock %}

{% block content %}
    
    <table class="table table-dark table-hover">
            
                
    {% for question in latest_question_list %}

    
    <tr><td><a href="{% url 'polls:detail' question.id %}" style = "color: beige; text-decoration: none;">{{ question.question_text }}</a>
    </td></tr>
{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/album.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>All Albums</h3>
    <table class="table table-dark table-hover">
            
        {% for a in albums %}

        <tr>
            <td><a href = "{% url 'tunes:specific_album' a.id %}">{{ a.title }}</a>  </td> <td> {{ a.numtracks }} </td>
        </tr>

        {% endfor %}
        
    </table>
{% endblock %}


django-mytunes/mysite/tunes/templates/tunes/albumdetail.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>Tracks in Album: {{ album }}</h3>
    <table class="table table-dark table-hover">
        
        
        {% for track in album.track_set.all %}

        <tr>
            <td> <a href="{% url 'tunes:specific_track' track.id %}">{{ track }}</a></td>
        </tr>

        {% endfor %}
    </table>

{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/artist.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>All Artists</h3>
    <table class="table table-dark table-hover">
        <th>  
        {% for artist in artists %}

    
        <tr>
            <td> <a href = "{% url 'tunes:specific_artist' artist.id %}">{{ artist.name }}</a> </td> <td>{{ artist.numtracks }}</td>
        </tr>

        {% endfor %}
    </table>

{% endblock %}


django-mytunes/mysite/tunes/templates/tunes/artistdetail.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>Tracks by {{ artist.name }}</h3>
    <table class="table table-dark table-hover" name = "Tracks">
            

        {% for track in trackslist %}
        <tr>
            
            <td> <a href="{% url 'tunes:specific_track' track.id %}">{{ track }}</a></td>

        </tr>
        {% endfor %}


    </table>

    <h3>Albums by {{ artist.name }}</h3>

    <table class="table table-dark table-hover" name = "Albums">

            
                
        {% for a in albumslist %}
        <tr>
            <td> <a href="{% url 'tunes:specific_album' a.id %}">{{ a }}</a></td>
        </tr>
        {% endfor %}


    </table>
{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/base_template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title> mytunes </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>


    <body>

        <nav class = "navbar navbar-expand-lg bg-dark navbar-dark py-3">
            <div class="container">
                <a href = "#" class = "navbar-brand" > 
                    My Tunes 
                </a>
    
                <button class="navbar-toggler" type = "button" data-bs-toggle="collapse" data-bs-target = "#navmenu"> 
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id = "navmenu">
                    <ul class="navbar-nav ms-auto">
                        
                        <li class="nav-item">
                            <a href="/tunes" class="nav-link">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href = "/tunes/artist" class = "nav-link">
                                Artists
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href = "/tunes/album" class = "nav-link">
                                Albums
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href = "/tunes/genre" class = "nav-link">
                                Genres
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href = "/tunes/playlist" class = "nav-link">
                                Playlists
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href = "/tunes/track" class = "nav-link">
                                Tracks
                            </a>
                        </li>
                        <li class = "nav-item">
                            <a href="/accounts/logout">
                                Log Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            
        </nav>

        <section class="bg-dark text-light p-5 p-lg-0 pt-lg-5 m-5 text-center text-sm-start" id = "body">

            <div class="container pb-2" id = "content">
                <div class = "align-items-center">
                    {% load socialaccount %}

                    {% if user.is_authenticated %}
                    
                    <div>
                        <h1>{% block title %}{% endblock %}</h1>
                    </div>

                    <div>
                        <p>{% block description%}{% endblock %}</p>
                    </div>
                    
                    <div>
                        {% block content %}{% endblock %}
                    </div>
                    
                    {% else %}
                    <h3><a href="{% provider_login_url 'github' %}">Sign In</a></h3>
                    {% endif %}

                </div>
            </div>
        </section>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

django-mytunes/mysite/tunes/templates/tunes/genre.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>All Genres</h3>
    <table class="table table-dark table-hover">
                
        {% for g in genres %}

    
        <tr>
            <td><a href = "{% url 'tunes:specific_genre' g.id %}">{{ g.name }}</a></td>
        </tr>

        {% endfor %}
    </table>
{% endblock %}


django-mytunes/mysite/tunes/templates/tunes/genredetail.html
{% extends "tunes/base_template.html" %}

{% block content %}
    <h3>Songs In Genre</h3>
    <table class="table table-dark table-hover">
        
        {% for track in genre %}

        <tr>
            <td><a href="{% url 'tunes:specific_track' track.id %}">{{ track }}</a></td>
        </tr>

        {% endfor %}

    </table>
{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/home_page.html
{% extends "tunes/base_template.html" %}

{% block content %}

{% load socialaccount %}

{% if user.is_authenticated %}


<h3>Welcome <p style = "color:red;"> {{ user.username }}</p></h3>

<table class="table table-dark table-hover">
    <tr><td>
        <a href = "{% url 'tunes:all_artists' %}">Browse by Artist</a>
    </td></tr>
    
    <tr><td>
        <a href = "{% url 'tunes:all_albums' %}">Browse by Album</a>
    </td></tr>

    <tr><td>
        <a href = "{% url 'tunes:all_genres' %}">Browse by Genre</a>
    </td></tr>

    <tr><td>
        <a href = "{% url 'tunes:all_playlists' %}">Browse by Playlists</a>
    </td></tr>
        
    <tr><td>
        <a href = "{% url 'tunes:all_tracks' %}">Browse by Tracks</a>
    </td></tr>

    
        

</table>
{% else %}
<h3><a href="{% provider_login_url 'github' %}">Sign In</a></h3>
{% endif %}

{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/playlist.html
{% extends "tunes/base_template.html" %}



{% block content %}

    <h3>Your Playlists</h3>
    <table class="table table-dark table-hover">
        
                
        {% for p in playlists %}

        
        <tr>
            <td><a href = "{% url 'tunes:specific_playlist' p.id %}">{{ p.name }}</a></td>
        </tr>

        {% endfor %}

    
    </table>
    <h3>Shared Playlists</h3>
    <table class = "table table-dark table-hover">
            
        {% for sp in shared %}

            <tr>
                <td>
                    <a href = "{% url 'tunes:specific_playlist' sp.id%}">{{sp.name}}</a>
                </td>
            </tr>
        {% endfor %}
        
    </table>
    <p>Want to create a new playlist?</p>

    <form action="." method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
            <label for="name">Name of New Playlist <span style = "color: yellow;">{{ msg }}</span></label>
            <input name = "name" type="text" id="name" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

{% endblock %}


django-mytunes/mysite/tunes/templates/tunes/playlistdetail.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>Tracks in {{ playlist.name }}</h3>
    <table class="table table-dark table-hover">
            
    {% for thing in playlist.tracks.all %}


    <tr>
        <td><a href="{% url 'tunes:specific_track' thing.id %}">{{ thing }}</a></td>
    </tr>

    {% endfor %}

    </table>
    
    <p>Want to share this playlist? Click <a href="{% url 'tunes:share_specific' playlist.id %}">here</a></p>    

    <p>Want to add a new track?</p>

    <form action="." method="post">
        
        {% csrf_token %}
        
        <select name = "track" id = "sel1" class = "form-control" required>
            <option disabled selected value> -- select an option -- </option>
            <div class="form-group mb-2">
                {% for track in tracks %}
                <option value = "{{ track.id }}"> {{ track }}</option>
                {% endfor %}
            </div>
        </select>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}


django-mytunes/mysite/tunes/templates/tunes/sharespecific.html
{% extends "tunes/base_template.html" %}

{% block content %}

{% load socialaccount %}

{% if user.is_authenticated %}

{% else %}
<h3><a href="{% provider_login_url 'github' %}">Sign In</a></h3>
{% endif %}

<h3> You chose to share this playlist, {{ playlist.name }} </h3>

<p>Now, you must decide who you want to share this with :D </p>

<p>Remember that you can only share with a person once<p>

    <form action="." method="post">
        {% csrf_token %}
        
        <div class="form-group mb-2">
            <label for="name">Name of other Users</label>
            <select name = "name" id = "name" class = "form-control" required>
                <div class="form-group mb-2">
                    {% for user in allusers %}
                    <option value = "{{ user.id }}"> {{ user }}</option>
                    {% endfor %}
                </div>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/track.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <h3>All Tracks</h3>
    <table class="table table-dark table-hover">
            
        {% for t in tracks %}

    
        <tr>
            <td title="Composer">{{ t.composer }}</td> <td title = "Title"><a href = "{{t.id}}">{{ t.name }}</a></td> <td title="milliseconds"> {{ t.milliseconds }}</td>
        </tr>

        {% endfor %}

        
    </table>

{% endblock %}

django-mytunes/mysite/tunes/templates/tunes/trackdetail.html
{% extends "tunes/base_template.html" %}



{% block content %}
    <table class="table table-dark table-hover">
            
        <tr>Track: {{track.name}}</tr>        
            
        <tr>
            <td>Composer: <a href="{% url 'tunes:specific_artist' track.album.artist_id %}">{{track.composer}}</a></td>
        </tr>

        <tr>
            <td>Genre: <a href="{% url 'tunes:specific_genre' track.genre_id %}"> {{track.genre}}</a></td>
        </tr>

        <tr>
            <td>Album: <a href="{% url 'tunes:specific_album' track.album_id %}">{{track.album}}</a></td>
        </tr>

        <tr>
            <td>Time in milliseconds: {{track.milliseconds}}</td>
        </tr>
    </table>
{% endblock %}